version: "3.7"
services:
  server:
    # restart: always
    build: .
    volumes:
      - ./:/code
      - /code/node_modules
    environment:
      - mongoport=27017
      - serverport=3000
    ports:
      - 3000:3000
  mongodb:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    logging:
      driver: none
